import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        faster: {
          black: 'var(--faster-color-black)',
          white: 'var(--faster-color-white)',
          neutral: {
            700: 'var(--faster-color-neutral-700)',
            600: 'var(--faster-color-neutral-600)',
            500: 'var(--faster-color-neutral-500)',
            400: 'var(--faster-color-neutral-400)',
            300: 'var(--faster-color-neutral-300)',
            200: 'var(--faster-color-neutral-200)',
            100: 'var(--faster-color-neutral-100)',
            50: 'var(--faster-color-neutral-50)',
          },
          primary: {
            700: 'var(--faster-color-primary-700)',
            600: 'var(--faster-color-primary-600)',
            500: 'var(--faster-color-primary-500)',
            400: 'var(--faster-color-primary-400)',
            300: 'var(--faster-color-primary-300)',
            200: 'var(--faster-color-primary-200)',
            100: 'var(--faster-color-primary-100)',
            50: 'var(--faster-color-primary-50)',
          },
          auxiliary: {
            700: 'var(--faster-color-auxiliary-700)',
            600: 'var(--faster-color-auxiliary-600)',
            500: 'var(--faster-color-auxiliary-500)',
            400: 'var(--faster-color-auxiliary-400)',
            300: 'var(--faster-color-auxiliary-300)',
            200: 'var(--faster-color-auxiliary-200)',
            100: 'var(--faster-color-auxiliary-100)',
            50: 'var(--faster-color-auxiliary-50)',
          },
          danger: {
            DEFAULT: 'var(--faster-color-danger-default)',
            hover: 'var(--faster-color-danger-hover)',
            700: 'var(--faster-color-danger-700)',
            600: 'var(--faster-color-danger-600)',
            500: 'var(--faster-color-danger-500)',
            400: 'var(--faster-color-danger-400)',
            300: 'var(--faster-color-danger-300)',
            200: 'var(--faster-color-danger-200)',
            100: 'var(--faster-color-danger-100)',
            50: 'var(--faster-color-danger-50)',
          },
          warning: {
            700: 'var(--faster-color-warning-700)',
            600: 'var(--faster-color-warning-600)',
            500: 'var(--faster-color-warning-500)',
            400: 'var(--faster-color-warning-400)',
            300: 'var(--faster-color-warning-300)',
            200: 'var(--faster-color-warning-200)',
            100: 'var(--faster-color-warning-100)',
            50: 'var(--faster-color-warning-50)',
          },
          success: {
            700: 'var(--faster-color-success-700)',
            600: 'var(--faster-color-success-600)',
            500: 'var(--faster-color-success-500)',
            400: 'var(--faster-color-success-400)',
            300: 'var(--faster-color-success-300)',
            200: 'var(--faster-color-success-200)',
            100: 'var(--faster-color-success-100)',
            50: 'var(--faster-color-success-50)',
          },
          info: {
            700: 'var(--faster-color-info-700)',
            600: 'var(--faster-color-info-600)',
            500: 'var(--faster-color-info-500)',
            400: 'var(--faster-color-info-400)',
            300: 'var(--faster-color-info-300)',
            200: 'var(--faster-color-info-200)',
            100: 'var(--faster-color-info-100)',
            50: 'var(--faster-color-info-50)',
          },
          'text-primary': 'var(--faster-color-text-primary)',
          'text-secondary': 'var(--faster-color-text-secondary)',
          'text-inverse': 'var(--faster-color-text-inverse)',
          border: 'var(--faster-color-border)',
          'border-strong': 'var(--faster-color-border-strong)',
          accent: 'var(--faster-color-accent)',
          'accent-hover': 'var(--faster-color-accent-hover)',
          'focus-ring': 'var(--faster-color-focus-ring)',
        },
      },
    },
  },
  plugins: [],
};

export default config;
